# Generated by Django 5.0.1 on 2024-03-06 09:58

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_url', models.URLField()),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('name_uk', models.CharField()),
                ('name_en', models.CharField()),
                ('description_uk', models.TextField()),
                ('description_en', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('trailer_url', models.URLField(validators=[django.core.validators.RegexValidator('^(http(s)?:\\/\\/)?(www\\.)?youtube\\.com\\/watch\\?v=([a-zA-Z0-9_-]+)')])),
                ('is_3d', models.BooleanField(default=False)),
                ('is_2d', models.BooleanField(default=False)),
                ('is_imax', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilmImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
