# Generated by Django 5.0.1 on 2024-03-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmimage_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmimage',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
