# Generated by Django 5.0.1 on 2024-03-06 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_filmimage_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 5)),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date(2024, 3, 13)),
        ),
    ]
