# Generated by Django 5.0.1 on 2024-03-27 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_end_date_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date(2024, 4, 3)),
        ),
    ]
