# Generated by Django 5.0.1 on 2024-03-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_film_end_date_alter_film_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='release_date',
        ),
    ]
