@startuml Database Relationship Diagram

rectangle "Location" as location {
    entity "City" as city {
        id: int <<generated>>
        --
        name: varchar
    }

    entity "Country" as country {
        id: int <<generated>>
        --
        name: varchar
    }   
}

rectangle "Auth" as auth {
    entity "User" as user {
        id: int <<generated>>
        --
        city_id: int <<FK>>
        first_name: varchar
        last_name: varchar
        nick_name: varchar
        email: varchar
        password: varchar
        card_number: bigint
        language: enum
        sex: enum
        phone: bigint
        birth_date: date
        created_at: datetime
    }
}

rectangle "News Letter" as news_letter {
    entity "SMS News Letter" as sms_news_letter {
        id: int <<generated>>
        --
        is_selective: boolean
        description: text
        status: enum
    }

    entity "Email News Letter" as email_news_letter {
        id: int <<generated>>
        --
        template_id: int <<FK>>
        is_selective: boolean
        status: enum
    }

    entity "Template" as template {
        id: int <<generated>>
        --
        name: varchar
        description: text
    }

    template::id ||--|{ email_news_letter::template_id
}

rectangle "Movie Theater" as movie_theater {
    entity "Main Page SEO" as main_page_seo {
        id: int <<generated>>
        --
        seo_description: text
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Main Page SEO phones" as main_page_seo_phones {
        id: int <<generated>>
        --
        main_page_seo_id: int <<FK>>
        number: bigint
    }

    entity "Theater" as theater {
        id: int <<generated>>
        --
        city_id: int <<FK>>
        name: varchar
        coordinates: point
        description: text
        logo_url: varchar 
        banner_url: varchar
        contacts: jsonb
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Theater Image" as theater_image {
        id: int <<generated>>
        --
        theater_id: int <<FK>>
        url: varchar
    }

    entity "Hall" as hall {
        id: int <<generated>>
        --
        theater_id: int <<FK>>
        number: smallint
        description: text
        scheme_url: varchar 
        banner_url: varchar
        rows: smallint
        columns: smallint
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Hall Image" as hall_image {
        id: int <<generated>>
        --
        hall_id: int <<FK>>
        url: varchar
    }

    entity "Seat" as seat {
        id: int <<generated>>
        --
        hall_id: int <<FK>>
        row: smallint
        column: smallint
        is_free: boolean
    }

    rectangle "Movie" as movie {
        entity "Film" as film {
            id: int <<generated>>
            --
            description: text
            year: int
            budget: int
            age_limit: smallint
            duration: smallint
            image_url: varchar
            trailer_url: varchar
            type: enum
            seo_url: varchar
            seo_title: varchar
            seo_keywords: varchar
            seo_description: varchar
        }

        entity "Genre" as genre {
            id: int <<generated>>
            --
            name: varchar
        }
        
        entity "Person" as person {
            id: int <<generated>>
            --
            first_name: varchar
            last_name: varchar
        }

        entity "Compositor" as compositor {
            id: int <<generated>>
            --
            person_id: int <<FK>>
        }

        entity "Producer" as producer {
            id: int <<generated>>
            --
            person_id: int <<FK>>
        }

        entity "Director" as director {
            id: int <<generated>>
            --
            person_id: int <<FK>>
        }

        entity "Scenarist" as scenarist {
            id: int <<generated>>
            --
            person_id: int <<FK>>
        }

        entity "Operator" as operator {
            id: int <<generated>>
            --
            person_id: int <<FK>>
        }

        film::id }|--|{ genre::id
        film::id }o--|{ country::id

        person::id ||--o| compositor::id
        person::id ||--o| producer::id
        person::id ||--o| director::id
        person::id ||--o| scenarist::id
        person::id ||--o| operator::id

        film::id }|--|{ compositor::id
        film::id }|--|{ producer::id
        film::id }|--|{ director::id
        film::id }|--|{ scenarist::id
        film::id }|--|{ operator::id
    }

    entity "Session" as session {
        id: int <<generated>>
        --
        film_id: int <<FK>>
        hall_id: int <<FK>>
        time: datetime
    }

    entity "Reservation" as reservation {
        id: int <<generated>>
        --
        user_id: int <<FK>>
        session_id: int <<FK>>
        seat_id: int <<FK>>
        status: enum
    }

    entity "Discount" as discount {
        name: varchar
        description: text
        banner_url: varchar
        video_url: varchar
        is_active: boolean
        created_at: date
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Discount Image" as discount_image {
        id: int <<generated>>
        --
        dicount_id: int <<FK>>
        url: varchar
    }

    entity "News" as news {
        id: int <<generated>>
        --
        name: varchar
        description: text
        banner_url: varchar
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "News Image" as news_image {
        id: int <<generated>>
        --
        news_id: int <<FK>>
        url: varchar
    }

    entity "Advertisement" as advertisement {
        id: int <<generated>>
        --
        name: varchar
        description: text
        banner_url: varchar
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Advertisement Image" as advertisement_image {
        id: int <<generated>>
        --
        advertisement_id: int <<FK>>
        url: varchar
    }

    entity "Cafe Bar" as cafe_bar {
        id: int <<generated>>
        --
        theater_id: int <<FK>>
        name: varchar
        description: text
        banner_url: varchar
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Cafe Bar Image" as cafe_bar_image {
        id: int <<generated>>
        --
        cofe_bar_id: int <<FK>>
        url: varchar
    }

    entity "Vip Hall" as vip_hall {
        id: int <<generated>>
        --
        theater_id: int <<FK>>
        name: varchar
        description: text
        banner_url: varchar
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Vip Hall Image" as vip_hall_image {
        id: int <<generated>>
        --
        vip_hall_id: int <<FK>>
        url: varchar
    }

    entity "Child Room" as child_room {
        id: int <<generated>>
        --
        theater_id: int <<FK>>
        name: varchar
        description: text
        banner_url: varchar
        seo_url: varchar
        seo_title: varchar
        seo_keywords: varchar
        seo_description: varchar
    }

    entity "Child Room Image" as child_room_image {
        id: int <<generated>>
        --
        child_room_id: int <<FK>>
        url: varchar
    }

    main_page_seo::id ||--o{ main_page_seo_phones::main_page_seo_id

    theater_image::theater_id }o--|| theater::id
    theater::city_id }o--|| location.city::id

    hall::theater_id }|--|| theater::id
    hall_image::hall_id }|--|| hall::id

    seat::hall_id }|--|| hall::id

    session::film_id }o--|| movie.film::id
    session::hall_id }o--|| hall::id

    reservation::user_id }o--|| auth.user::id
    reservation::session_id }o--|| session::id
    reservation::seat_id }o--|| seat::id

    discount_image::dicount_id }o--|| discount::id 

    news_image::news_id }o--|| news::id

    advertisement_image::advertisement_id }o--|| advertisement::id

    cafe_bar::theater_id }o--|| theater::id
    cafe_bar_image::cofe_bar_id }o--|| cafe_bar::id

    vip_hall::theater_id }o--|| theater::id
    vip_hall_image::vip_hall_id }o--|| vip_hall::id

    child_room::theater_id }o--|| theater::id
    child_room_image::child_room_id }o--|| child_room::id
}

location.city::id ||--o{ auth.user::city_id

auth.user::id }|--o{ news_letter.sms_news_letter::id
auth.user::id }|--o{ news_letter.email_news_letter::id

@enduml