# Generated by Django 5.0.1 on 2024-02-27 11:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_bannersettings_are_advertisements_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersettings',
            options={},
        ),
        migrations.AlterField(
            model_name='bannersettings',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
